chore: [EXT-3324] Remove integration tests
contentful/ui-extensions-sdk pull request #1089
Opened 2021-11-23 15:14 UTC by loweisz

# Purpose of PR

Removing the integration test suite

## PR Checklist

- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Typescript typings are added/updated/not required

2021-11-24 13:16 UTC, Jwhiles approved these changes

2021-11-24 13:24 UTC, andipaetzold reviewed
Following dependencies can be removed:
* `async-retry`
* `@tyes/async-retry`
* `ts-node`
* `dotenv`
* `nanoid`

Other stuff:
* `.gitignore` & `eslintignore` still contains `cypress` paths
* unit tests shouldn't use the cypress docker image, but build with `cimg/node` idealy
* CYPRESS_INSTALL_BINARY can be removed
* Cypress can be removed from dependabot config
* README should be updated as it still mentions cypress

2021-11-24 13:28 UTC, andipaetzold requested changes
See comment above

2021-11-24 14:31 UTC, andipaetzold approved these changes

2021-11-25 08:57 UTC, colomolo approved these changes

2021-11-26 10:43 UTC, merged