feat: entry list result data validation and tests
contentful/ui-extensions-sdk pull request #1215
Opened 2022-03-16 07:26 UTC by bgutsol

2022-03-18 10:22 UTC, andipaetzold requested changes
Looks good. Just some nits.

2022-03-18 10:22 UTC, andipaetzold commented on lib/entry-list.ts
> +    }
Nit: vs code proposes to convert this to an async function, maybe we can do that to get some newer-looking code

2022-03-18 10:22 UTC, andipaetzold commented on lib/entry-list.ts
>  const isFunction = (f: any) => typeof f === 'function'
Can we extract this as it's also used in `app.ts`?
Or maybe inline the function directly as it's so trivial?

2022-03-18 10:22 UTC, andipaetzold commented on lib/entry-list.ts
> +const validateResult = (result: OnEntryListUpdatedHandlerReturn) => {
It feels strange that the method returns a value which is always identical to the input or throws an error.
I'd make this an assert method that never returns anything but throws if something is wrong.

Now it feels like it's also doing some data cleanup or similar

2022-03-18 10:22 UTC, andipaetzold commented on lib/entry-list.ts
> +      throw new Error(`EntryListResult data is invalid. Invalid value of key "${key}"`)
```suggestion
      throw new Error(`EntryListResult data is invalid. Invalid value of key "${key}".`)
```

2022-03-18 10:22 UTC, andipaetzold commented on test/unit/entry-list.spec.ts
> +      it('returns false if the result data hasn`t valid key', () =>
```suggestion
      it('returns false if the result data has invalid key', () =>
```

2022-03-18 10:22 UTC, andipaetzold commented on test/unit/entry-list.spec.ts
> +      it('returns false if the result data hasn`t valid values type', () =>
```suggestion
      it('returns false if the result data has an invalid value type', () =>
```

2022-03-21 10:39 UTC, bgutsol commented
> Looks good. Just some nits.

@andipaetzold thanks a lot for the feedback! 
Please check one more time to be sure I understood you right.

2022-03-21 11:07 UTC, andipaetzold approved these changes

2022-03-21 11:09 UTC, merged