fix: [] improved types for ParametersAPI
contentful/ui-extensions-sdk pull request #1236
Opened 2022-04-11 09:18 UTC by Jwhiles

# Purpose of PR
The previous type we used in the parameters API would not allow you to read any properties. This PR brings the type in line with the return value of the `getParameters` method. 

## PR Checklist

- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Typescript typings are added/updated/not required

2022-04-11 09:47 UTC, andipaetzold requested changes

2022-04-11 12:01 UTC, Jwhiles commented on lib/types/api.types.ts
> +  invocation?: KeyValueMap
I think if that's the existing behaviour then we should probably set invocation to any. We don't want to have types that don't reflect reality, but we don't want to break existing apps.

2022-04-12 07:02 UTC, shikaan approved these changes

2022-04-12 07:28 UTC, andipaetzold approved these changes

2022-04-12 13:18 UTC, merged

2022-05-10 05:57 UTC, Chaoste commented
These changes unfortunately introduced breaking changes. Strangely, the types don't overlap with ours, so we're using an 'unknown' conversion.
See [here](https://github.com/contentful/workflows-marketplace-app/blob/48b06c4ba7c52b7d6c00c51c32833468ba9453de/src/locations/Dialog/DialogRouter.tsx#L24-L28) how we define the invocation parameters type and [here](https://app.circleci.com/pipelines/github/contentful/workflows-marketplace-app/3525/workflows/b62a91ef-c7b4-42ea-ace0-43dd399b050f/jobs/24628) the types errors. For some reasons, the types are not overlapping :/