feat: [EXT-3684] add home location api to app-sdk
contentful/ui-extensions-sdk pull request #1322
Opened 2022-07-18 12:29 UTC by martin3walker

# Purpose of PR
We need to add a home location to the app sdk in order to support the new custom environment home functionality being added to the web app.

## PR Checklist

- [ ] Tests are added/updated/not required
- [ ] Tests are passing
- [ ] Typescript typings are added/updated/not required

2022-07-18 14:15 UTC, andipaetzold requested changes

2022-07-18 14:15 UTC, andipaetzold commented on lib/types/api.types.ts
> +  | PageExtensionSDK
```suggestion
  | HomeExtensionSDK
```

2022-07-20 08:11 UTC, andipaetzold approved these changes

2022-07-27 09:46 UTC, colomolo approved these changes
lgtm

2022-08-10 09:40 UTC, merged