feat: do not bundle package [EXT-3598]
contentful/ui-extensions-sdk pull request #1590
Opened 2023-07-12 13:29 UTC by colomolo

# Purpose of PR

* Removing bundling to single `.js` file for UI Extensions support. Will build with `tsc` only for apps.
* Removed docs/styleguide
* Target ES2020

## PR Checklist
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Typescript typings are added/updated/not required

2023-07-17 13:31 UTC, ghepting approved these changes
LGTM but would love for @andipaetzold to review!

2023-07-17 14:00 UTC, andipaetzold requested changes
* Update .gitignore to not mention files in `dist`
* Update the styleguide to not mention the css in `dist` (or remove the whole styleguide)

2023-07-20 11:58 UTC, andipaetzold approved these changes

2023-07-21 13:08 UTC, ghepting approved these changes

2023-07-21 13:15 UTC, merged