chore: fix space.waitUntilAssetProcessed typing
contentful/ui-extensions-sdk pull request #337
Opened 2020-09-07 09:14 UTC by anho

# Purpose of PR

The `space.waitUntilAssetProcessed` was wrong as it is async in the implementation but sync in the typing.

## PR Checklist

- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Typescript typings are added/updated/not required

2020-09-07 09:15 UTC, giotiskl approved these changes
💯

2020-09-08 08:08 UTC, jelz approved these changes

2020-09-08 08:08 UTC, davidfateh reviewed
We should bump the package minor version number too.

2020-09-08 08:11 UTC, anho commented
@davidfateh I couldn't remember if you have automatic releases for this repo. Will bump minor then.

2020-09-08 08:22 UTC, jelz requested changes
We've got 3.20 bump in master which wasn't published yet, please revert and jump on the train

2020-09-08 08:22 UTC, jelz commented
3.21, sorry

2020-09-08 08:23 UTC, anho commented
Just a typo? Master is 3.21.0

2020-09-08 08:24 UTC, anho commented
It seems I was too slow 
![image](https://user-images.githubusercontent.com/863612/92451785-7c047000-f1bd-11ea-8b23-8432a69a0fcc.png)

2020-09-08 08:25 UTC, jelz approved these changes
versions here and there, iterate so fast, many wowz :exploding_head:

2020-09-08 08:25 UTC, jelz approved these changes
versions here and there, iterate so fast, many wowz :exploding_head:

2020-09-08 08:26 UTC, merged