Fix: [] update create contentType function with optional id
contentful/ui-extensions-sdk pull request #859
Opened 2021-07-14 15:03 UTC by loweisz

The id will be generated automatically when not passed so we can make it optional.

## PR Checklist

- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Typescript typings are added/updated/not required

2021-07-16 09:48 UTC, kdamball approved these changes

2021-07-16 10:42 UTC, andipaetzold requested changes
Please revert package-lock.json and run `npm install` with npm 6

2021-07-19 15:00 UTC, andipaetzold approved these changes

2021-07-22 13:48 UTC, andipaetzold approved these changes

2021-07-23 14:42 UTC, merged